[Books.The_Rust_Programming_Language]
print_url="https://doc.rust-lang.org/book/print.html"
file_name="the_rust_programming_language.pdf"

[Books.High_Assurance_Rust]
print_url="https://highassurance.rs/print.html"
file_name="high_assurance_rust.pdf"

[Books.Nomicon]
print_url="https://doc.rust-lang.org/nomicon/print.html"
file_name="nomicon.pdf"

[Books.Rust_Cookbook]
print_url="https://rust-lang-nursery.github.io/rust-cookbook/print.html"
file_name="cookbook.pdf"

[Books.RustWash]
print_url="https://rustwasm.github.io/docs/book/print.html"
file_name="rust_wasm.pdf"

[Books.EasyRust]
print_url="https://dhghomon.github.io/easy_rust/print.html"
file_name="easy_rust.pdf"

[Books.EmbeddedRust]
print_url="https://docs.rust-embedded.org/book/print.html"
file_name="embedded_rust_book.pdf"

[Books.RustReference]
print_url="https://doc.rust-lang.org/reference/print.html"
file_name="rust_reference.pdf"

[Books.ClI]
print_url="https://rust-cli.github.io/book/print.html"
file_name="rust_cli.pdf"
